### ISSUE TITLE
Printer quotes ruin your day

### ISSUE THREAD

**Issue by dmerand** [dansmith65/FileMaker-JSON#7]
Hi,

I love this JSON module, and I use it all the time! I've noticed that it dies when parsing JSON containing printers' quotes (“”), which often aren't escaped in the same way as "regular" (") quotes. You may want to put in a check for those, because they are sneaky and will ruin your day (as they did mine).

**Comment by dansmith65** [comment]
That's interesting; apparently FileMaker lumps curly quotes in with "regular" quotes in a standard comparison; in other words, it reads them as the same: `"\“" = "\""`

Replacing that test with `Equals ( "\“" ; "\"" )` returns false, which is what I need to do in a few different places in the module.

Thanks for pointing this out; I'm glad this module has been useful for you!
